# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: nuc01 # You need to replace this with your own namespace
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://myuser:mypassword@postgres.nuc01.svc.cluster.local:5432/mydb'
  PASSWORD_SECRET: 12j3i4j8rfe9ueafds # You need to replace this with your own secret like random string
