apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-<YOUR_NAMESPACE>
  labels:
    volume: postgres-pv-<YOUR_NAMESPACE>
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgres
  persistentVolumeReclaimPolicy: Retain
