apiVerison: v1
type: Deployment
metadata:
  name: react-web
  namespace: nuc01 # You need to replace this with your own namespace
spec:
  replicas: 3
  selector:
    app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      containers:
        - name: react
          images: <your_docker_hub_repository>/<your_docker_image_name>:latest # You need to replace this with your own Docker Hub repository and image name
          ports:
           - containerPort: 5173 # React Default Port
          envFrom:
            - configMapRef:
                name: frontend-cm
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
