apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-svc
  namespace: <your_namespace>
spec:
  selector:
    app: nginx-proxy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30123
  type: NodePort
