apiVersion: v1
type: Service
metadata:
  name: frontend-svc
  namespace: nuc01 # You need to replace this with your own namespace
spec:
  selector:
    app: react-web
  ports:
    - port: 80
      targetPort: 5173
  type: ClusterIP